makspll/bevy_mod_scripting

bevy_mod_scripting/Cargo.toml
bevy_mod_scripting/assets/scripts/event_recipients.lua
bevy_mod_scripting/examples/complex_game_loop.rs
bevy_mod_scripting/examples/console_integration_lua.rs
bevy_mod_scripting/examples/console_integration_rhai.rs
bevy_mod_scripting/examples/event_recipients.rs
bevy_mod_scripting/src/hosts/mod.rs
bevy_mod_scripting/src/hosts/rhai_host/mod.rs
bevy_mod_scripting/src/hosts/rlua_host/mod.rs
readme.md

- Closes #4 
- Changes both Lua and Rhai public API, events now require a `recipients` field

add event recipient functionality

---

.github/workflows/ci.yml

change ci.yml

---

Cargo.toml
languages/bevy_mod_scripting_lua/Cargo.toml

I noticed that while `mlua` supports the `async` feature (and it's bubbled up through `tealr`), this project did not support enabling it. I don't know if this was a conscious design choice, so feel free to reject this if so.

Add mlua/async feature support

---

Cargo.toml

Fixes #49
If some other version of lua is desired for docs.rs, then tell me and I'll change it.

Enable lua54 feature for docs.rs

---

.github/workflows/ci.yml

Adds a CI step which:
- pulls the "docs.rs" features metadata from the root crate
- passes those to `cargo doc --workspace --features=<features>` and runs the documentation build
- this step should fail PR's if documentation doesn't build
Issue identified in #49

add new CI step for documentation checking

---

languages/bevy_mod_scripting_lua/Cargo.toml
languages/bevy_mod_scripting_lua/src/docs.rs

Teal has an issue where using getters and setters causes duplicate fields to appear in the type definition file. This is treated by the teal compiler as an error and prevents using the generated types. This broke the game of life example for teal.
the temporary fix should deal with duplicate fields for now

Add hotfix to deal with duplicate fields in teal

---

readme.md

Fixes #57 
Instead of including the image in the package, I made it fall back to the file hosted on github. This make it show up in generated doc, but the img src in teh file displayed on github is the same.
Credit for solution: <https://daily-dev-tips.com/posts/html-fallback-images-on-error/>

Add fallback logo image pointing to github

---

bevy_mod_scripting_core/src/hosts.rs
bevy_mod_scripting_core/src/systems.rs
languages/bevy_mod_scripting_lua/src/lib.rs
languages/bevy_mod_scripting_rhai/src/lib.rs

Allows for flexibility in custom hosts, see #65.

changing handle_events in the ScriptHost trait to be a mut method

---

bevy_script_api/src/common/bevy/mod.rs
bevy_script_api/src/sub_reflect.rs

I've run into a few panics with world access if you happen to hold on to entity values between frames. I'm not certain this is the ideal way to handle them, so feel free to suggest changes or go with an alternate implementation if desired.

check if entity exists before accessing

---

Cargo.toml
assets/scripts/multiple_events_rhai.rhai
examples/rhai/multiple_events_rhai.rs
languages/bevy_mod_scripting_lua_derive/src/derive_flags/auto_methods.rs
languages/bevy_mod_scripting_rhai/Cargo.toml
languages/bevy_mod_scripting_rhai/src/lib.rs

This should fix #75 
Also added a new example for Rhai.

Fix bug in Rhai Event Handler

---

bevy_mod_scripting_core/src/world.rs
languages/bevy_mod_scripting_lua/src/lib.rs
languages/bevy_mod_scripting_rhai/src/lib.rs

Resolves #82 
Prevents `WorldPointer`s from seeing an invalid `*mut World` by wrapping it in an `Option` that gets `take`n when the original `WorldPointerGuard` gets dropped.
Also adding a couple of blocking variants of the existing `read`/`write` methods since I'm not in love with the current panic-rather-than-block semantics. I would probably advocate for inverting them and block by default, but I didn't want to shake things up too much.

guard the WorldPointer against UB

---

Cargo.toml
languages/bevy_mod_scripting_lua/Cargo.toml

#91's patch method doesn't work for downstream projects unless they also include the patch. This time I actually tested that my downstream project builds off this version.

Switched to git dependancy pin rather than patch for tealr

---

crates/bevy_script_api/src/common/bevy/mod.rs
crates/bevy_script_api/src/core_providers.rs
crates/bevy_script_api/src/lua/bevy/mod.rs
crates/bevy_script_api/src/lua/util.rs
crates/bevy_script_api/src/rhai/bevy/mod.rs

Fixes #20 
Adds API methods for dynamic queries, using the new QueryBuilder added in Bevy 0.13.
Both Lua and Rhai have implementations as well as types for Teal.
Lua:
```lua
local ComponentOne = world:get_type_by_name("ComponentOne")
local ComponentTwo = world:get_type_by_name("ComponentTwo")
local ComponentThree = world:get_type_by_name("ComponentThree")
local ComponentFour = world:get_type_by_name("ComponentFour")
-- `world:query` accepts any number of `LuaTypeRegistration`
-- returns a `LuaQueryBuilder` which can be used to further filter the query with the `:with` and `:without` methods
-- `LuaQueryBuilder` has an `:iter` method which resolves the query and returns an iterator over the entities and components
for entity, componentOne, componentTwo in world:query(ComponentOne, …
```

Dynamic Queries

---

readme.md

Example lead to 404, this fixes that

Fix Broken Example

---

.github/workflows/release-plz.yml
CHANGELOG.md
release-plz.toml

- Because releasing takes forever and I am lazy
- Addresses #132

Integrate Release Plz

---

crates/languages/bevy_mod_scripting_lua/src/docs.rs

Hotfix for 2 bugs in the teal environment generation algorithm: 
* Fixed fields not being deduped correctly because `Vec::dedup` only dedupes *consecutive* duplicate items. This was done by sorting the fields list beforehand. 
* Also deduped static fields while I was at it, though I'm not sure if those are used? 
* Fixed the algorithm not properly escaping record fields/functions/methods/etc that share the name of an existing Lua/Teal keyword.  This was coming up since the `Uuid` record has a function called `nil` for making an all-zero uuid. 
Note that this still doesn't completely fix Teal document generation when using the default Bevy APIs since they're still missing a definition for `ReflectedValue`, but I'll likely need some guidance on that and will split that off to a separate PR.

Documentation generation hotfixes

---

.github/workflows/bevy_api_gen.yml
.github/workflows/bevy_mod_scripting.yml
.github/workflows/release-plz.yml

I want to start using pre-release versions

Run release-plz on staging too

---

crates/languages/bevy_mod_scripting_lua/src/util.rs

I don't know why it only started failing now 🤷

Fix failing doctest

---

crates/bevy_mod_scripting_core/src/context.rs

Exposes script contexts to public consumers,
Don't see many reasons not to

feat: make script contexts public

---

crates/bevy_mod_scripting_core/src/bindings/world.rs

Just a convenience method I found useful.
I removed some panic comments on the with_component_*() because I don't believe they panic, but I didn't affirm that with tests.

feat: Add world.with_or_insert_component_mut()

---

crates/bevy_mod_scripting_core/Cargo.toml
crates/bevy_mod_scripting_core/src/bindings/function/arg_info.rs
crates/bevy_mod_scripting_core/src/bindings/function/mod.rs
crates/bevy_mod_scripting_core/src/bindings/function/script_function.rs
crates/bevy_mod_scripting_core/src/bindings/world.rs
crates/bevy_mod_scripting_core/src/error.rs
crates/bevy_mod_scripting_core/src/handler.rs
crates/languages/bevy_mod_scripting_rhai/Cargo.toml
crates/languages/bevy_mod_scripting_rhai/src/bindings/script_value.rs

Adds support for non-required arguments, with default values passed in during a call:
```rust
#[test]
fn test_optional_argument_not_required() {
let fn_ = |a: usize, b: Option<usize>| a + b.unwrap_or(0);
let script_function = fn_.into_dynamic_script_function();
with_local_world(|| {
let out = script_function
.call(vec![ScriptValue::from(1)], FunctionCallContext::default())
.unwrap();
assert_eq!(out, ScriptValue::from(1));
});
}
```
Also bumps rhai version to actual release

feat: Add `optional` arguments to script functions

---

crates/languages/bevy_mod_scripting_lua/src/bindings/script_value.rs
crates/languages/bevy_mod_scripting_lua/tests/data/hashmap/can_pass_and_return_hashmap.lua
crates/languages/bevy_mod_scripting_rhai/src/bindings/script_value.rs
crates/languages/bevy_mod_scripting_rhai/tests/data/hashmap/can_pass_and_return_hashmap.rhai
crates/script_integration_test_harness/src/test_functions.rs

This now allows for interesting serialization use cases

feat: add `ScriptValue::Map` and create appropriate conversions in lua and rhai

---

crates/bevy_mod_scripting_core/src/bindings/access_map.rs
release-plz.toml

This was a typo which caused clashes in the reflect allocation ID space, meaning things would appear locked when they shouldn't have

fix: prevent allocation and component ID ranges from overlapping

---

.github/workflows/bevy_mod_scripting.yml
Cargo.toml
badges/coverage.svg
crates/bevy_mod_scripting_core/Cargo.toml
crates/bevy_mod_scripting_functions/Cargo.toml
crates/languages/bevy_mod_scripting_lua/Cargo.toml
crates/languages/bevy_mod_scripting_rhai/Cargo.toml
docs/src/Summary/installation.md
release-notes/0.9.0.md

Bumps to non pre-release version

chore: bump from prerelease

---

Cargo.toml
crates/bevy_api_gen/Cargo.bootstrap.toml
makefile
readme.md

Bumps bindings and supported bevy version to 0.15.1

fix: bump `bevy` to 0.15.1

---

.github/workflows/missing-documentation-reminder.yml

Adds a cron job which will synchronize the missing documentation issue with PR's needing documentation

chore: add documentation reminder issue tracker

---

crates/bevy_mod_scripting_core/Cargo.toml
crates/bevy_mod_scripting_core/src/asset.rs
crates/bevy_mod_scripting_core/src/lib.rs
crates/languages/bevy_mod_scripting_lua/src/lib.rs
crates/languages/bevy_mod_scripting_rhai/src/lib.rs

fix: add missing extensions in the asset loader

---

crates/bevy_mod_scripting_core/src/lib.rs

The module contains no public items anyway and makes docs a bit more confusing.

fix: make `extractors` module non-public

---

crates/bevy_mod_scripting_core/src/commands.rs
crates/bevy_mod_scripting_core/src/extractors.rs
crates/bevy_mod_scripting_core/src/handler.rs
crates/bevy_mod_scripting_core/src/lib.rs
crates/bevy_mod_scripting_core/src/script.rs
docs/src/Summary/running-scripts.md
examples/game_of_life.rs

Adds scripts which do not get attached to entities but can still be run.
Fixes #249

feat: add static scripts which do not need to be attached to entities to be run

---

.github/workflows/bevy_mod_scripting.yml
Cargo.toml
crates/bevy_mod_scripting_core/Cargo.toml
crates/bevy_mod_scripting_core/src/bindings/function/mod.rs
crates/bevy_mod_scripting_core/src/bindings/function/namespace.rs
crates/bevy_mod_scripting_core/src/bindings/function/script_function.rs
crates/bevy_mod_scripting_core/src/docgen/info.rs
crates/bevy_mod_scripting_derive/Cargo.toml
crates/bevy_mod_scripting_derive/readme.md
crates/bevy_mod_scripting_derive/src/lib.rs
release-plz.toml
src/lib.rs

Closes #264 
Adds a macro which can be used to generate registrator functions for an impl block i.e.:
```rust
#[test]
fn test_macro_generates_correct_registrator_function() {
#[derive(Reflect)]
struct TestStruct;
#[script_bindings(bms_core_path = "crate", name = "test_fn")]
impl TestStruct {
/// My docs !!
fn test_fn(_self: Ref<TestStruct>, mut _arg1: usize) {}
}
let mut test_world = bevy::ecs::world::World::default();
register_test_fn(&mut test_world);
let app_registry = test_world
.get_resource::<AppScriptFunctionRegistry>()
.unwrap();
let app_registry = app_registry.read();
let test_fn = app_registry
.get_function(TestStruct::into_namespace(), "test_fn")
.unwrap();
assert_eq!(test_fn.info.docs, Some("My docs !!".into()));
assert_eq!(test_fn.info.arg_info.len(), 2);
assert_eq!( …
```

feat: Add `script_bindings` impl block derive macro

---

crates/bevy_mod_scripting_core/src/bindings/function/arg_meta.rs
crates/bevy_mod_scripting_core/src/bindings/function/mod.rs
crates/bevy_mod_scripting_core/src/bindings/function/script_function.rs
crates/bevy_mod_scripting_core/src/docgen/info.rs
crates/bevy_mod_scripting_core/src/docgen/mod.rs
crates/bevy_mod_scripting_core/src/docgen/typed_through.rs

Adds inlined type information on each argument and return type for later use in docgen

feat: add `TypedThrough` abstraction to function meta, and refactor

---

crates/bevy_mod_scripting_core/src/bindings/function/script_function.rs
crates/xtask/src/main.rs

Adds tracy features by default to local as well as CI checks and fixes the current build errors.
Fixes #275

fix: `tracy` compile errors and add tracy buid to CI

---

crates/bevy_mod_scripting_core/Cargo.toml
crates/bevy_mod_scripting_core/src/bindings/function/arg_meta.rs
crates/bevy_mod_scripting_core/src/bindings/function/from.rs
crates/bevy_mod_scripting_core/src/bindings/function/mod.rs
crates/bevy_mod_scripting_core/src/bindings/function/type_dependencies.rs
crates/bevy_mod_scripting_core/src/bindings/query.rs
crates/bevy_mod_scripting_core/src/bindings/reference.rs
crates/bevy_mod_scripting_core/src/bindings/world.rs
crates/bevy_mod_scripting_core/src/docgen/typed_through.rs
crates/bevy_mod_scripting_core/src/error.rs
crates/bevy_mod_scripting_functions/src/core.rs
crates/ladfile/src/lib.rs
crates/ladfile_builder/src/lib.rs
crates/languages/bevy_mod_scripting_lua/tests/data/construct/construct_enum.lua
crates/languages/bevy_mod_scripting_lua/tests/data/construct/construct_struct.lua
crates/languages/bevy_mod_scripting_lua/tests/data/construct/construct_tuple_struct.lua
crates/languages/bevy_mod_scripting_rhai/tests/data/construct/simple_enum.rhai
crates/languages/bevy_mod_scripting_rhai/tests/data/construct/simple_struct.rhai
crates/languages/bevy_mod_scripting_rhai/tests/data/construct/simple_tuple_struct.rhai
crates/testing_crates/test_utils/src/test_data.rs

Makes this possible:
```lua
local type = world.get_type_by_name("SimpleEnum")
-- Struct Variant
local constructed = construct(type, {
variant = "Struct",
foo = 123
})
assert(constructed:variant_name() == "Struct", "Value was constructed incorrectly, expected constructed.variant to be Struct but got " .. constructed:variant_name())
assert(constructed.foo == 123, "Value was constructed incorrectly, expected constructed.foo to be 123 but got " .. constructed.foo)
-- TupleStruct Variant
local constructed = construct(type, {
variant = "TupleStruct",
_1 = 123
})
assert(constructed:variant_name() == "TupleStruct", "Value was constructed incorrectly, expected constructed.variant to be TupleStruct but got " .. constructed:variant_name())
assert(constructed._1 == 123, "Value was constructed …
```

feat: add `construct` global for constructing arbitrary types & `Union` type

---

.github/workflows/bevy_mod_scripting.yml
crates/bevy_mod_scripting_core/src/lib.rs
crates/xtask/src/main.rs

Less of a bug fix and more of a feature, since this technically works as bevy intended, but not having the feature is a bit of a foot gun
Fixes #299

feat: pre-register reflected components with the world at finalize

---

crates/bevy_mod_scripting_core/src/bindings/function/script_function.rs
crates/bevy_mod_scripting_core/src/bindings/world.rs
crates/xtask/src/main.rs

Fixes #300 
Introduces a more convenient world access scope function which is less of a footgun, especially in macros!
Don't drink and proc macro kids

fix: functions not releasing accesses correctly on error

---

crates/bevy_mod_scripting_core/src/event.rs

Love seeing all your releases and progress of late! This is tiny thing, it just permits a trailing comma when defining callback labels using the macro.

feat: Allow trailing comma in callback_labels.

---

crates/bevy_mod_scripting_derive/src/derive/into_script.rs

This is why we need a prelude 🧐 . I missed a path section in the derive implementation of IntoScript

fix: Generate IntoScript implementation with the correct path

---

crates/bevy_mod_scripting_functions/src/core.rs

Should allow:
```lua
local map = map({})
```
i.e. lua cannot make the distinction between an empty table and hashmap normally
Addresses https://github.com/makspll/bevy_mod_scripting/pull/328

feat: create global `map` for allowing empty hashmap construction

---

crates/bevy_mod_scripting_core/src/bindings/function/from_ref.rs
crates/bevy_mod_scripting_core/src/reflection_extensions.rs
crates/languages/bevy_mod_scripting_lua/tests/data/set/set_primitives_works.lua
crates/languages/bevy_mod_scripting_rhai/tests/data/set/set_primitives_works.rhai
crates/testing_crates/test_utils/src/test_data.rs

Addresses #324, with limitations.
I.e. reflection still doesn't support actually indexing into maps

feat: support setting hashmaps via reflection

---

crates/bevy_mod_scripting_core/src/bindings/function/from.rs
crates/bevy_mod_scripting_core/src/bindings/function/mod.rs
crates/bevy_mod_scripting_core/src/bindings/function/script_function.rs
crates/bevy_mod_scripting_functions/src/core.rs

The fix in #329 didn't fully work as the returned value would STILL be just a map, instead a more geneorus `FromScript` implementation should do the trick, without necessitating a new function call

fix: remove `map` global and instead allow hashmap `FromScript` from list of tuples

---

crates/languages/bevy_mod_scripting_lua/tests/data/construct/construct_unit_struct.lua
crates/languages/bevy_mod_scripting_rhai/tests/data/construct/unit_struct.rhai
crates/testing_crates/test_utils/src/test_data.rs

Pushing this PR up so we can document how to construct unit structs. The first commit of this PR will fail with:
```
---- script_test - lua - /construct/construct_unit_struct.lua ----
error: Error in function construct : Error converting argument 2: Value mismatch, expected: std::collections::HashMap<alloc::string::String, bevy_mod_scripting_core::bindings::script_value::ScriptValue, std::collections::hash_map::RandomState>, got: [].
Context:
stack traceback:
[C]: in function 'construct'
[string "crates/languages/bevy_mod_scripting_lua/src/l..."]:2: in main chunk
```
Not sure how to get this to work without passing dummy values like this:
```lua
local type = world.get_type_by_name("UnitStruct")
local constructed = construct(type, {
dummy = true
})
assert(constructed ~= nil, "Value was not …
```

feat: add test for construct using unit struct

---

crates/lad_backends/mdbook_lad_preprocessor/Cargo.toml
crates/lad_backends/mdbook_lad_preprocessor/src/argument_visitor.rs
crates/lad_backends/mdbook_lad_preprocessor/src/markdown.rs
crates/lad_backends/mdbook_lad_preprocessor/src/sections.rs
crates/ladfile_builder/src/plugin.rs
docs/book.toml

feat(lad): export global functions in `lad` exported plugin & add collapsible sections to pre-processor

---

.github/pull_request_template.md
.github/workflows/pr-titles.yml
docs/src/Examples/introduction.md
docs/src/SUMMARY.md

Just highlights that these exist without needing people to dig through the repo,
also adds a pr template with useful information

docs: add links to examples in the book

---

.github/workflows/bevy_mod_scripting.yml
crates/bevy_mod_scripting_core/src/bindings/globals/core.rs
crates/bevy_mod_scripting_core/src/bindings/globals/mod.rs
crates/bevy_mod_scripting_core/src/bindings/mod.rs
crates/bevy_mod_scripting_core/src/lib.rs
crates/bevy_mod_scripting_derive/src/derive/mod.rs
crates/bevy_mod_scripting_derive/src/derive/script_bindings.rs
crates/bevy_mod_scripting_derive/src/derive/script_globals.rs
crates/bevy_mod_scripting_derive/src/lib.rs
crates/bevy_mod_scripting_functions/src/core.rs
crates/ladfile_builder/src/lib.rs
crates/ladfile_builder/src/plugin.rs
crates/languages/bevy_mod_scripting_lua/src/lib.rs
crates/languages/bevy_mod_scripting_rhai/src/lib.rs
crates/xtask/src/main.rs
examples/docgen.rs

- Adds `AppScriptGlobalRegistry`
- Pushes responsibility of registering globals up to BMS core
- Does not cover all globals, as `entity`, `world` and `script_id` have more complex requirements, these will be taken care of later, probably by being moved to actual functions (which will also avoid needlessly allocating entities)
- Makes `ladfile_builder` export globals to the ladfile format as defined earlier
- This is now visible in the global docs
- Also adds `script_globals` derive macro, but I am not sure how useful that's going to be
addresses: #322

feat(bms,ladfile_builder): introduce app global instance registry and export them in `ladfile_builder`

---

assets/tests/map_get/can_get_hashmap_value copy.rhai
assets/tests/map_get/can_get_hashmap_value.lua
crates/bevy_mod_scripting_core/src/reflection_extensions.rs
crates/bevy_mod_scripting_functions/src/core.rs

- Adds `map_get` binding
- Same signature as `get` but is a temporary stop gap for the lack of support for reflecting into hashmaps from  `get` (due to missing functionality upstream in Bevy)
- The values are returned by value not by reference
- Adds some docs around the area
```lua
local Resource = world.get_type_by_name("TestResourceWithVariousFields")
local resource = world.get_resource(Resource)
assert(resource.string_map:map_get("foo") == "bar", "Expected bar, got " .. resource.string_map:map_get("foo"))
```
Came out from the discussion around #341

feat: add `map_get` function for cloning and returning values from a map

---

crates/bevy_mod_scripting_core/src/bindings/globals/core.rs

- The change in #340, made the plugin registration order matter
- This PR moves global extraction to `App::finalize` meaning it will happen after everything is registered with the type registry

fix: plugin registration order affecting which globals are exported

---

crates/languages/bevy_mod_scripting_lua/src/lib.rs
crates/languages/bevy_mod_scripting_rhai/src/lib.rs

- Currently on a script re-load, the entire context will be replaced for both lua and rhai
- This does not work well with shared context mode
- There probably isn't any harm to not doing this normally either
- I.e. scripts shouldn't hold much global state, and if they do it might be beneficial to re-load while retaining that state
- Ultimately the script lifecycle should take care of re-freshing the state correctly
- This PR makes script re-loads merge the new and old contexts instead of wiping the old one and installing the new one

fix!: script contexts being completely overwritten on a re-load

---

.github/workflows/pr-titles.yml
release-plz.toml

- Adds `refactor` scope
- Allows explicitly skipping changelog in commits via `[SKIP_CHANGELOG]`

chore: add more commit scopes

---

assets/tests/api_availability/api_available_on_callback.lua
assets/tests/api_availability/api_available_on_callback.rhai
assets/tests/api_availability/api_available_on_callback_and_on_load__RETURN.lua
assets/tests/api_availability/api_available_on_callback_and_on_load__RETURN.rhai
assets/tests/api_availability/api_available_on_script_load.lua
assets/tests/api_availability/api_available_on_script_load.rhai
assets/tests/pop/vec.rhai
crates/languages/bevy_mod_scripting_rhai/src/lib.rs
crates/testing_crates/script_integration_test_harness/src/lib.rs

- Test suite wasn't catching this as it wasn't asserting that callbacks actually run in certain tests
- This is now going to be caught, tests with "__RETURN" in the name are expected to return true for all test callbacks
- This allows us to actually confidently assert certain meta logic
- Rhai now works correctly

fix: rhai reloading behavior regression from #345 [SKIP_CHANGELOG]

---

crates/bevy_mod_scripting_core/src/bindings/schedule.rs
crates/bevy_mod_scripting_core/src/commands.rs
crates/bevy_mod_scripting_core/src/context.rs
crates/bevy_mod_scripting_core/src/error.rs
crates/bevy_mod_scripting_core/src/extractors.rs
crates/bevy_mod_scripting_core/src/handler.rs
crates/bevy_mod_scripting_core/src/lib.rs
crates/bevy_mod_scripting_core/src/runtime.rs
crates/bevy_mod_scripting_core/src/script.rs
crates/languages/bevy_mod_scripting_lua/src/lib.rs
crates/languages/bevy_mod_scripting_rhai/Cargo.toml
crates/languages/bevy_mod_scripting_rhai/src/lib.rs
crates/languages/bevy_mod_scripting_rhai/tests/rhai_tests.rs
crates/testing_crates/script_integration_test_harness/src/lib.rs
crates/testing_crates/test_utils/src/test_plugin.rs

This is a part of the ongoing work towards #244 
the goal of this PR is to be able to have multiple parallel systems, access scripts separately with just read access while being able to call them.
At the same time we clean up the number of resources required, and simplify the retrieval of contexts.
The changes are:
- remove `ScriptContexts` completely
- All contexts are stored as a `Arc<Mutex<C>>` and don't need to be `Sync` anymore
- Runtimes are no longer passed around as `&mut` but with `&` i.e. it's up to the language host implementer to decide how to make the runtime thread safe
- For rhai, `Engine` gets wrapped in `RwLock`, and since you can call scripts with just `&Engine` this is fine for parallel script calls 
- ~The context trait gets some trampolining traits to convert between …

refactor!: Merge `ScriptContexts<T>` into `Scripts<T>` + Remove `Sync` bound from Contexts

---

crates/bevy_mod_scripting_core/src/reflection_extensions.rs

Currently reflecting into an enum with a unit variant value, will create a `ScriptValue::Unit` on the script side, i.e. nil for lua.
This is not great because it means you lose information about the variant.
This PR fixes the bug causing this.

fix: unit enum variants other than `Option::None` being converted into `ScriptValue::Unit`

---

release-plz.toml

- enter PR summary here
- what did you change
- why did you do it this way?
- Are there alternative ways we need to keep in mind?
- Did you write tests to cover new or modified behavior?
- These are not necessary, but very welcome
- I am always happy to receive any PR's, but adding tests makes it easier for me to merge them!
- This crate uses `release-plz` to manage our deploys
- A CI check will verify your PR title to make sure it uses a valid conventional prefix like:
- `feat: {title}` - corresponds to `Added` heading in changelog, backwards compatibile changes
- `fix: {title}` - corresponds to `Fixed` heading in changelog, fixes bugs or bad behavior
- `chore: {title}` - does not appear in the changelog, useful for "meta" work that doesn't affect the API
- `docs: {title}` - does not …

chore: revert release-plz to older config

---

crates/bevy_system_reflection/Cargo.toml
crates/bevy_system_reflection/readme.md

Adds missing cargo data for the cargo publish

chore: add cargo metadata to bevy_system_reflection

---

crates/bevy_mod_scripting_core/src/lib.rs
crates/bevy_mod_scripting_core/src/script.rs

Just had to call `register_type` for `ScriptComponent` and add `#[reflect(Component)]`

feat: allow lua scripts to insert ScriptComponent

---

crates/bevy_mod_scripting_core/src/asset.rs
crates/bevy_mod_scripting_core/src/lib.rs
crates/languages/bevy_mod_scripting_lua/src/lib.rs
crates/languages/bevy_mod_scripting_rhai/src/lib.rs
docs/src/SUMMARY.md
docs/src/ScriptSystems/introduction.md
docs/src/ScriptingReference/constructing-arbitrary-types.md
docs/src/ScriptingReference/introduction.md
docs/src/Summary/controlling-script-bindings.md
docs/src/Summary/managing-scripts.md
docs/src/Summary/running-scripts.md
docs/src/Summary/script-id-mapping.md

Replaces the mapper struct with a hash map, improves the `App` and `ScriptPlugin` traits so that one can choose to add additional extensions easilly in a predictable place either via:
*App*
```rust
app.add_supported_script_extensions(self.additional_supported_extensions, self.language.clone());
```
or *ScriptingPlugin*
```rust
app.add_plugins(
LuaScriptingPlugin.set_additional_supported_extensions(&["my_ext"])
)
``` 
Also adds a bunch of docs

feat: Add missing `luau` extension, improve extension configuration options

---

crates/bevy_api_gen/src/context.rs
crates/bevy_api_gen/src/passes/cache_traits.rs
crates/bevy_mod_scripting_core/src/bindings/access_map.rs
crates/bevy_mod_scripting_core/src/bindings/function/arg_meta.rs
crates/bevy_mod_scripting_core/src/bindings/function/from_ref.rs
crates/bevy_mod_scripting_core/src/bindings/function/into.rs
crates/bevy_mod_scripting_core/src/bindings/function/into_ref.rs
crates/bevy_mod_scripting_core/src/bindings/function/mod.rs
crates/bevy_mod_scripting_core/src/bindings/function/type_dependencies.rs
crates/bevy_mod_scripting_core/src/bindings/globals/mod.rs
crates/bevy_mod_scripting_core/src/bindings/mod.rs
crates/bevy_mod_scripting_core/src/bindings/pretty_print.rs
crates/bevy_mod_scripting_core/src/bindings/query.rs
crates/bevy_mod_scripting_core/src/bindings/reference.rs
crates/bevy_mod_scripting_core/src/bindings/world.rs
crates/bevy_mod_scripting_core/src/docgen/mod.rs
crates/bevy_mod_scripting_core/src/lib.rs
crates/bevy_mod_scripting_core/src/private/mod.rs

where we previously did `pub use my_mod` we also use `pub use my_mod::*`, this should make imports everywhere prettier and should not be a breaking change.
However removing some of the items which were previously `pub` by making them `pub (crate)` might be.
- stop using the hidden macros

feat!: shorten import paths, hide private macros

---

crates/bevy_mod_scripting_core/src/bindings/function/arg_meta.rs
crates/bevy_mod_scripting_core/src/bindings/function/from.rs
crates/bevy_mod_scripting_core/src/bindings/function/into.rs
crates/bevy_mod_scripting_core/src/bindings/function/mod.rs
crates/bevy_mod_scripting_core/src/bindings/function/type_dependencies.rs
crates/bevy_mod_scripting_core/src/private/mod.rs
crates/bevy_mod_scripting_derive/src/derive/get_type_dependencies.rs
crates/bevy_mod_scripting_derive/src/derive/mod.rs
crates/bevy_mod_scripting_derive/src/lib.rs

Currently the `GetTypeDependencies` trait struggles with deeply nested container types.
For example `HashMap<Result<T,E>,V>` would place bounds of `GetTypeRegistration` on `Result` which quickly falls apart with non-`'static` types like `Ref` and `Mut` which don't have `GetTypeRegistration` implementations.
This overhaul introduces the concept of an `Underlying` type allowing us to have two type trees, the `Real` types which we want to end up being registered in the registry, and the `Facade` types which exist purely as trait carriers:
```mermaid
graph TD;
subgraph facade
A1[HashMap<.Val<.T>>] --> A2["`Val<.T>`"]
A2 --> T
end
subgraph underlying
B1[HashMap<.T>] --> B2["`T`"]
end
```
Thanks to that we can make the two assertions confidently:
- I want your REAL types in the script function …

feat!: re-design `GetTypeDependencies` trait & add `GetTypeDependencies` derive macro

---

assets/tests/globals/type_cache_available.lua
assets/tests/globals/type_cache_available.rhai
crates/bevy_mod_scripting_core/src/bindings/globals/core.rs
crates/bevy_mod_scripting_core/src/bindings/globals/mod.rs
crates/bevy_mod_scripting_core/src/bindings/world.rs
crates/bevy_mod_scripting_functions/src/core.rs

using `get_type_by_name` is slightly cumbersome. In order to not repeat yourself AND avoid polluting globals, you need to call:
```lua
local Type = world.get_type_by_name("MYType")
```
in EVERY callback, or alternatively do it once at the top of your script, but doing that goes against the advice to not run code in the body of the script outside of any functions.
this PR adds a global `types` cache, which lets you do:
```lua
types.MyType
```
or for more complex types:
```lua
types["MyGenericType<MyOtherType>"]
```
The types populated in the cache are equivalent to the types available as static globals with the addition of generic types.
The change makes use of changes in #369 to correctly type this global as `HashMap<String, ScriptComponentRegistration | ScriptResourceRegistration | …

feat: add global `types` cache making `get_type_by_name` redundant

---

crates/bevy_mod_scripting_core/src/bindings/globals/core.rs
crates/bevy_mod_scripting_core/src/bindings/globals/mod.rs
crates/bevy_mod_scripting_core/src/docgen/info.rs
crates/bevy_mod_scripting_core/src/docgen/typed_through.rs
crates/bevy_mod_scripting_core/src/reflection_extensions.rs
crates/lad_backends/mdbook_lad_preprocessor/src/argument_visitor.rs
crates/lad_backends/mdbook_lad_preprocessor/src/markdown.rs
crates/lad_backends/mdbook_lad_preprocessor/src/sections.rs
crates/lad_backends/mdbook_lad_preprocessor/tests/books/example_ladfile/expected/parent/lad/globals.md
crates/ladfile/src/lib.rs
crates/ladfile/test_assets/test.lad.json
crates/ladfile_builder/src/lib.rs
crates/ladfile_builder/src/plugin.rs

For now globals in the ladfile didn't really support values other than "static" instances, i.e. you could only place a `LadTypeId` in the global namespace, meaning it would have to be a pure type, and not something like `Vec<T>`.
This change allows anything in the globals that would be allowed in function arguments.
This also improves the formatting in the globals section:
- Types mentioned link to their detail sections
- Static instances are separated from non-static instances, to make it easier to read
- Descriptive text is provided

feat(ladfile): improve globals in LAD format

---

crates/bevy_mod_scripting_core/src/asset.rs

fixes regression introduced in https://github.com/makspll/bevy_mod_scripting/pull/366 which caused the default extensions not to be correctly populated

fix: supported extensions not including default extensions [SKIP_CHANGELOG]

---

crates/bevy_mod_scripting_core/src/bindings/pretty_print.rs

- Means printing reflect types containing script values will print them nicer

feat: add ScriptValue override for printing opaque values

---

assets/benchmarks/function/call.lua
assets/benchmarks/function/call.rhai
assets/benchmarks/function/call_4_args.lua
assets/benchmarks/function/call_4_args.rhai
assets/benchmarks/math/vec_mat_ops.lua
assets/benchmarks/math/vec_mat_ops.rhai
assets/benchmarks/query/1000_entities.lua
assets/benchmarks/query/1000_entities.rhai
assets/benchmarks/query/100_entities.lua
assets/benchmarks/query/100_entities.rhai
assets/benchmarks/query/10_entities.lua
assets/benchmarks/query/10_entities.rhai
assets/benchmarks/reflection/10.lua
assets/benchmarks/reflection/10.rhai
assets/benchmarks/reflection/100.lua
assets/benchmarks/reflection/100.rhai
crates/testing_crates/script_integration_test_harness/Cargo.toml
crates/testing_crates/script_integration_test_harness/src/lib.rs
crates/testing_crates/script_integration_test_harness/src/test_functions.rs
crates/xtask/src/main.rs

- Adds more interesting benchmarks around querying and reflection, revealing slower parts of BMS and/or Bevy
- Re-create all plots based on benchmarks present every push to main

chore: add query and reflection benchmarks

---

assets/tests/query/dynamic_component_query.lua
assets/tests/query/dynamic_component_query.rhai

- Adds tests for queries on dynamic components

test: add dynamic component query tests

---

assets/tests/globals/type_cache_available.lua
assets/tests/globals/type_cache_available.rhai
crates/bevy_mod_scripting_core/src/bindings/globals/core.rs
crates/testing_crates/script_integration_test_harness/src/lib.rs
crates/testing_crates/test_utils/src/test_data.rs

`types["GenericType<String>"]` should work now, this was using `ident` instead of `short_path` by mistake

fix: fix global type cache not containing generic types

---

.github/workflows/bencher_on_pr_or_fork.yml
.github/workflows/bencher_on_pr_or_fork_closed.yml
.github/workflows/bencher_on_pr_or_fork_upload.yml
Cargo.toml
benches/benchmarks.rs
crates/xtask/src/main.rs

- Runs bencher on PR's as per instructions at https://bencher.dev/docs/how-to/github-actions/

chore: run bencher on PR or fork

---

.github/workflows/bencher_on_pr_or_fork_upload.yml
crates/lad_backends/mdbook_lad_preprocessor/src/lib.rs
crates/lad_backends/mdbook_lad_preprocessor/tests/books/example_ladfile/book.toml
docs/book.toml

- These were broken on the github.io url after I made the links absolute

fix: mdbook preprocessor links not taking into account root url

---

Cargo.toml
benches/benchmarks.rs
crates/bevy_mod_scripting_core/src/bindings/function/script_function.rs
crates/testing_crates/script_integration_test_harness/src/lib.rs
crates/testing_crates/test_utils/src/test_data.rs
crates/xtask/src/main.rs

Adds `xtask` utilities for profiling a specific benchmark, as well as a feature which plays nicely with bevy's.
I tried using an independent `profiling` setup but I think this one is the least confusing and most in line with what bevy consumers will already be familiar with

feat: add `profile_with_tracy` feature which plays nicely with bevy's `bevy/trace_tracy` feature

---

.github/workflows/bencher_on_pr_or_fork_closed.yml
Cargo.toml
benches/benchmarks.rs
crates/bevy_mod_scripting_core/Cargo.toml
crates/bevy_mod_scripting_core/src/asset.rs
crates/bevy_mod_scripting_core/src/bindings/function/from.rs
crates/bevy_mod_scripting_core/src/bindings/function/into.rs
crates/bevy_mod_scripting_core/src/bindings/function/into_ref.rs
crates/bevy_mod_scripting_core/src/bindings/function/namespace.rs
crates/bevy_mod_scripting_core/src/bindings/function/script_function.rs
crates/bevy_mod_scripting_core/src/bindings/globals/core.rs
crates/bevy_mod_scripting_core/src/bindings/globals/mod.rs
crates/bevy_mod_scripting_core/src/bindings/query.rs
crates/bevy_mod_scripting_core/src/bindings/schedule.rs
crates/bevy_mod_scripting_core/src/bindings/script_component.rs
crates/bevy_mod_scripting_core/src/bindings/script_system.rs
crates/bevy_mod_scripting_core/src/bindings/script_value.rs
crates/bevy_mod_scripting_core/src/bindings/world.rs
crates/bevy_mod_scripting_core/src/commands.rs
crates/bevy_mod_scripting_core/src/docgen/info.rs
crates/bevy_mod_scripting_core/src/lib.rs
crates/bevy_mod_scripting_core/src/runtime.rs
crates/bevy_mod_scripting_core/src/script.rs
crates/testing_crates/script_integration_test_harness/src/lib.rs
crates/testing_crates/script_integration_test_harness/src/test_functions.rs
crates/testing_crates/test_utils/src/lib.rs
crates/xtask/src/main.rs
tests/script_tests.rs

Overhauls tracing spans allowing neat visualisations like this one:
At the same time, expands benchmarks to cover ground on "marshalling" teritory, which seems to be a large bottleneck in performance.
Also adds utilities to xtask to allow seamless tracing of BMS benchmarks with `tracy`

feat: improve tracing spans, add `profile_with_tracy` feature flag

---

crates/bevy_mod_scripting_core/src/bindings/access_map.rs

Removes some unnecessary code in access maps to improve performance slightly.
Also refactors area slightly to make it easier to modify in the future

feat: optimize access map

---

crates/bevy_mod_scripting_core/src/bindings/access_map.rs

Tries a simpler hash function for access maps specifically.
The motivation is this:
- access maps are small, most often probably less than 10 items
- we don't care about collisions as much because of this
- we deal with simple u64 keys, which are unique by definition
So then:
- using these u64's as hashes directly should make lookups faster, and collisions won't be a big deal

perf: select better hashing algorithm for access maps

---

crates/bevy_mod_scripting_core/src/bindings/allocator.rs
crates/bevy_mod_scripting_core/src/bindings/function/script_function.rs

The function registry as well as the allocator used the standard `std` hashmap, which by default uses a secure but slow hash. We don't need to worry about security here, so switching to hashbrown should give us a fair bit of speed up for free.

perf: switch to hashbrown hashmap in the function registry

---

crates/bevy_mod_scripting_core/src/commands.rs
crates/bevy_mod_scripting_core/src/event.rs
crates/bevy_mod_scripting_core/src/handler.rs
crates/bevy_mod_scripting_core/src/lib.rs

Largely, this is a refactor of the `commands` module, we now use a shared command `RunScriptCallback` to initiate internal callbacks. This command can also be used by consumers of BMS removing the need to have a full blown system to initiate one off callbacks.
At the same time, this adds a `trigger_response` field to the script callback event, when this is set to true:
- Event handlers will emit a `ScriptCallbackResponseEvent` with the response payload from the script
- Just as the `RunScriptCallback` command will do the same
This should give users more flexibility in running "once-off" callbacks, especially if they require scripts to output something from them. At the moment the best bet is to either:
- have an event handler in a temporary schedule
- run custom logic with event handler …

feat: add option to emit response event on each callback  & `RunScriptCallback` command for "once-off" callbacks

---

crates/bevy_mod_scripting_core/src/bindings/pretty_print.rs
crates/bevy_mod_scripting_core/src/bindings/reference.rs

Cleans the code up a bit, moves reflect base constructors into that type, and guarantees that typeid always corresponds to a valid reflect type

refactor: refactor `ReflectReference` internally

---

crates/bevy_mod_scripting_derive/src/derive/get_type_dependencies.rs

The derive macro `GetTypeDependencies` required the `bevy_mod_scripting_core` to be an explicit dependency for users. 
I altered it to refer to `::bevy_mod_scripting::core` instead of `bevy_mod_scripting_core` so that it works with the usual dependency of `bevy_mod_scripting`.
The user can add "bevy_mod_scripting_core" as a dependency.
- It works in my project now.
- I did not add a test.
- I did run the tests; there were two unrelated failures that I looked into but it wasn't clear to me how to fix it.
```
error[E0433]: failed to resolve: could not find `function_scope` in `profiling`
--> crates/bevy_mod_scripting_core/src/bindings/globals/core.rs:29:20
|
29 |         profiling::function_scope!("app finish");
|                    ^^^^^^^^^^^^^^ could not find `function_scope` in …
```

fix: Derive `GetTypeDependency` without explicit "core" dependency.

---

assets/tests/insert_children/invalid_entity_errors.lua
assets/tests/insert_children/invalid_entity_errors.rhai
crates/bevy_mod_scripting_core/src/bindings/world.rs
crates/bevy_mod_scripting_core/src/error.rs
crates/lad_backends/mdbook_lad_preprocessor/src/sections.rs

Many places in BMS use `Entity::from_raw(0)` as an invalid entity, because that index is not naturally assigned to any entity in Bevy.
When an entity is not available in a callback, i.e. `on_script_loaded` people often try to interact with the entity global, this PR makes it so that using those entities, will throw a more meaningful error and point people to this fact.
Also fixes minor newline issue in docs

feat: improve errors when entity is unavailable

---

crates/bevy_mod_scripting_core/Cargo.toml

This was me fat-fingering commits

fix: `lua54` feature being forced

---

crates/bevy_mod_scripting_core/src/asset.rs

This change logs a warning when a ScriptAsset is loaded whose language is unknown. It does not alter any behavior.
> WARN A script "main.p8" was added but its language is unknown. Consider adding the "p8" extension to the `ScriptAssetSettings`.
I've had moments where scripts load but nothing happens and it's been tricky to track down. Hopefully this'll help me and other users.

feat: Warn on unknown language.

---

.github/workflows/bevy_mod_scripting.yml

Eventually this can be updated to work on forks (spit out a diff as a comment?) for now just going to skip on forks

chore: don't sync bindings on forks, as they fail

---

.github/workflows/bencher_on_pr_or_fork.yml
.github/workflows/bevy_mod_scripting.yml
.github/workflows/synchronize_bindings.yml
crates/bevy_mod_scripting_functions/src/lib.rs
crates/xtask/src/main.rs

Checks keep breaking on forks, just make sure these don't run on forks

chore: try fix CI for forks

---

crates/bevy_mod_scripting_core/src/bindings/script_system.rs
crates/bevy_mod_scripting_core/src/commands.rs
crates/bevy_mod_scripting_core/src/config.rs
crates/bevy_mod_scripting_core/src/context.rs
crates/bevy_mod_scripting_core/src/extractors.rs
crates/bevy_mod_scripting_core/src/lib.rs
crates/bevy_mod_scripting_core/src/runtime.rs
crates/languages/bevy_mod_scripting_lua/src/lib.rs
crates/languages/bevy_mod_scripting_rhai/src/lib.rs
crates/testing_crates/script_integration_test_harness/src/lib.rs

Does what #470 did with context loading settings but for the runtime.
Since it's this is something we initialize once and then purely read (or modify through read refs), it can fit this model.
This leaves only 2 resources in the handler context
`RuntimeSettings` and `RuntimeContainer` are removed, replace usages with `P::readonly_settings(world.id()).runtime)` access to initializers is no longer possible outside the plugin setup phase

refactor: remove `RuntimeContainer` & `RuntimeSettings`, add plugin runtime to static world local settings

---

crates/bevy_mod_scripting_core/src/bindings/script_system.rs
crates/bevy_mod_scripting_core/src/context.rs
crates/bevy_mod_scripting_core/src/extractors.rs
crates/bevy_mod_scripting_core/src/handler.rs
crates/languages/bevy_mod_scripting_lua/src/lib.rs
crates/languages/bevy_mod_scripting_rhai/src/lib.rs
crates/testing_crates/test_utils/src/test_plugin.rs

All of `ContextLoadFn` `ContextReloadFn` and `HandlerFn` now accept `WorldId` instead of directly requiring the properties available within the static config introduced in #470 . This simplifies signatures, removes the need to retrieve the runtime if you don't need one, and is all around more ergonomic
if you implemented a scripting plugin you will need to correct your function signatures for the above aliases, and fetch the config yourself to access callbacks via `Plugin::readonly_configuration(world_id)` using the world id you will now receive.

refactor: modify `ContextLoadFn` & `ContextReloadFn` & `HandlerFn` to use `WorldId` instead of direct config

---

crates/bevy_mod_scripting_core/src/asset.rs
crates/bevy_mod_scripting_core/src/bindings/script_system.rs
crates/bevy_mod_scripting_core/src/commands.rs
crates/bevy_mod_scripting_core/src/context.rs
crates/bevy_mod_scripting_core/src/event.rs
crates/bevy_mod_scripting_core/src/extractors.rs
crates/bevy_mod_scripting_core/src/handler.rs
crates/bevy_mod_scripting_core/src/script/script_context.rs
crates/languages/bevy_mod_scripting_lua/src/lib.rs
crates/languages/bevy_mod_scripting_rhai/src/lib.rs
crates/testing_crates/script_integration_test_harness/src/lib.rs
crates/testing_crates/script_integration_test_harness/src/scenario.rs
crates/testing_crates/test_utils/src/test_plugin.rs

- **ScriptContext API Changes**: Now wrapped in `Arc<RwLock<>>` - access via `.read()` and `.write()` methods; `get()` renamed to `get_context()`; New methods: `get_resident()`, `get_context_and_residency()`
- **HandlerContext Removed**: No longer available - replaced by direct access to `ScriptContext`; `with_handler_system_state()` function removed
- **CallContext Trait**: New trait implemented for all script contexts; Provides `call_context_dynamic()` and `call_context()` methods
- **GetPluginFor Trait**: All context types must now implement this trait; Provides reverse mapping from context to plugin type
- **Lua Type Changes**: Context type changed from `mlua::Lua` to `LuaContext` wrapper; Update all code interacting with Lua contexts
- **RunScriptCallback Changes**: …

refactor: remove `HandlerCtxt`, wrap `ScriptContext<P>` in Arc

---

benches/benchmarks.rs
crates/bevy_mod_scripting_bindings/src/globals/core.rs
crates/bevy_mod_scripting_bindings/src/globals/mod.rs
crates/bevy_mod_scripting_bindings/src/script_value.rs
crates/bevy_mod_scripting_derive/src/derive/script_globals.rs
crates/testing_crates/script_integration_test_harness/src/lib.rs

Adds warning logs when types have global duplicates

feat: warn on duplicate globals
